name: First Work Project No4
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get codes
              uses: actions/checkout@v2
            - name: Install nodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install dependencies
              run: |
                prop-types
                
            - name: Linting
              run: eslint --ext .jsx --fix src
            - name: Build
              run: vite build
            - name: Test
              run: vitest run