name: First Work Project No4
on: push
jobs:
    fourth-project:
        runs-on: ubuntu-latest
        steps:
            - name: Get codes
              uses: actions/checkout@v2
            - name: Install nodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install dependencies
              run: |
                npm ci
                npm install eslint
            - name: Linting
              run: npm r
            - name: Build
              run: vite build
            - name: Test
              run: vitest run
            - name: Deploy
              run: echo "Deployment success"